/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChannelIngest from './ChannelIngest';
import ChannelPackaging from './ChannelPackaging';
import ChannelPublishing from './ChannelPublishing';
import ChannelSignaling from './ChannelSignaling';
import ChannelTags from './ChannelTags';
import ChannelTranscode from './ChannelTranscode';

/**
 * The Channel model module.
 * @module model/Channel
 * @version 0.0.0
 */
class Channel {
    /**
     * Constructs a new <code>Channel</code>.
     * @alias module:model/Channel
     * @param ingest {module:model/ChannelIngest} 
     * @param transcode {module:model/ChannelTranscode} 
     */
    constructor(ingest, transcode) { 
        
        Channel.initialize(this, ingest, transcode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, ingest, transcode) { 
        obj['ingest'] = ingest;
        obj['transcode'] = transcode;
    }

    /**
     * Constructs a <code>Channel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Channel} obj Optional instance to populate.
     * @return {module:model/Channel} The populated <code>Channel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Channel();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('ingest')) {
                obj['ingest'] = ChannelIngest.constructFromObject(data['ingest']);
            }
            if (data.hasOwnProperty('labels')) {
                obj['labels'] = ApiClient.convertToType(data['labels'], ['String']);
            }
            if (data.hasOwnProperty('modified')) {
                obj['modified'] = ApiClient.convertToType(data['modified'], 'Date');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('packaging')) {
                obj['packaging'] = ChannelPackaging.constructFromObject(data['packaging']);
            }
            if (data.hasOwnProperty('publishing')) {
                obj['publishing'] = ChannelPublishing.constructFromObject(data['publishing']);
            }
            if (data.hasOwnProperty('region')) {
                obj['region'] = ApiClient.convertToType(data['region'], 'String');
            }
            if (data.hasOwnProperty('resource_class')) {
                obj['resource_class'] = ApiClient.convertToType(data['resource_class'], 'String');
            }
            if (data.hasOwnProperty('self')) {
                obj['self'] = ApiClient.convertToType(data['self'], 'String');
            }
            if (data.hasOwnProperty('signaling')) {
                obj['signaling'] = ChannelSignaling.constructFromObject(data['signaling']);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ChannelTags.constructFromObject(data['tags']);
            }
            if (data.hasOwnProperty('transcode')) {
                obj['transcode'] = ChannelTranscode.constructFromObject(data['transcode']);
            }
        }
        return obj;
    }


}

/**
 * An optional URL to a JSON Schema document describing this resource
 * @member {String} $schema
 */
Channel.prototype['$schema'] = undefined;

/**
 * Date and time the channel was created.
 * @member {Date} created
 */
Channel.prototype['created'] = undefined;

/**
 * External Channel ID provided at channel creation time
 * @member {String} id
 */
Channel.prototype['id'] = undefined;

/**
 * @member {module:model/ChannelIngest} ingest
 */
Channel.prototype['ingest'] = undefined;

/**
 * Optional labels for a channel. Any included labels must be at least 1 character long, but no greater than 256 characters. The maximum number of labels is 10.
 * @member {Array.<String>} labels
 */
Channel.prototype['labels'] = undefined;

/**
 * Date and time the channel was last modified.
 * @member {Date} modified
 */
Channel.prototype['modified'] = undefined;

/**
 * A friendly human-readable name for the channel. This will get displayed in user interfaces.
 * @member {String} name
 */
Channel.prototype['name'] = undefined;

/**
 * @member {module:model/ChannelPackaging} packaging
 */
Channel.prototype['packaging'] = undefined;

/**
 * @member {module:model/ChannelPublishing} publishing
 */
Channel.prototype['publishing'] = undefined;

/**
 * Region represents the general geolocation for transcoding and stream egress from iStreamPlanet. If no region is provided at channel creation time, then 'US_WEST' is used.
 * @member {module:model/Channel.RegionEnum} region
 */
Channel.prototype['region'] = undefined;

/**
 * If the ResourceClass is unspecified the channel will default to run in the 'DYNAMIC' ResourceClass. Note that changing the ResourceClass for a running channel is supported and will be performed with no downtime.
 * @member {module:model/Channel.ResourceClassEnum} resource_class
 */
Channel.prototype['resource_class'] = undefined;

/**
 * Self link for the channel.
 * @member {String} self
 */
Channel.prototype['self'] = undefined;

/**
 * @member {module:model/ChannelSignaling} signaling
 */
Channel.prototype['signaling'] = undefined;

/**
 * @member {module:model/ChannelTags} tags
 */
Channel.prototype['tags'] = undefined;

/**
 * @member {module:model/ChannelTranscode} transcode
 */
Channel.prototype['transcode'] = undefined;





/**
 * Allowed values for the <code>region</code> property.
 * @enum {String}
 * @readonly
 */
Channel['RegionEnum'] = {

    /**
     * value: "US_WEST"
     * @const
     */
    "WEST": "US_WEST",

    /**
     * value: "US_EAST"
     * @const
     */
    "EAST": "US_EAST"
};


/**
 * Allowed values for the <code>resource_class</code> property.
 * @enum {String}
 * @readonly
 */
Channel['ResourceClassEnum'] = {

    /**
     * value: "DYNAMIC"
     * @const
     */
    "DYNAMIC": "DYNAMIC",

    /**
     * value: "STATIC"
     * @const
     */
    "STATIC": "STATIC"
};



export default Channel;

