/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChannelPackagingContentProtectionAtlas from './ChannelPackagingContentProtectionAtlas';
import ChannelPackagingContentProtectionBulkFile from './ChannelPackagingContentProtectionBulkFile';
import ChannelPackagingContentProtectionCommon from './ChannelPackagingContentProtectionCommon';
import ChannelPackagingContentProtectionCpix from './ChannelPackagingContentProtectionCpix';
import ChannelPackagingContentProtectionKeyRotation from './ChannelPackagingContentProtectionKeyRotation';
import ChannelPackagingContentProtectionSimple from './ChannelPackagingContentProtectionSimple';

/**
 * The ChannelPackagingContentProtection model module.
 * @module model/ChannelPackagingContentProtection
 * @version 0.0.0
 */
class ChannelPackagingContentProtection {
    /**
     * Constructs a new <code>ChannelPackagingContentProtection</code>.
     * Configures how to protect packaged media segments.
     * @alias module:model/ChannelPackagingContentProtection
     */
    constructor() { 
        
        ChannelPackagingContentProtection.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChannelPackagingContentProtection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChannelPackagingContentProtection} obj Optional instance to populate.
     * @return {module:model/ChannelPackagingContentProtection} The populated <code>ChannelPackagingContentProtection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChannelPackagingContentProtection();

            if (data.hasOwnProperty('atlas')) {
                obj['atlas'] = ChannelPackagingContentProtectionAtlas.constructFromObject(data['atlas']);
            }
            if (data.hasOwnProperty('bulk_file')) {
                obj['bulk_file'] = ChannelPackagingContentProtectionBulkFile.constructFromObject(data['bulk_file']);
            }
            if (data.hasOwnProperty('common')) {
                obj['common'] = ChannelPackagingContentProtectionCommon.constructFromObject(data['common']);
            }
            if (data.hasOwnProperty('cpix')) {
                obj['cpix'] = ChannelPackagingContentProtectionCpix.constructFromObject(data['cpix']);
            }
            if (data.hasOwnProperty('key_rotation')) {
                obj['key_rotation'] = ChannelPackagingContentProtectionKeyRotation.constructFromObject(data['key_rotation']);
            }
            if (data.hasOwnProperty('sample_aes')) {
                obj['sample_aes'] = ApiClient.convertToType(data['sample_aes'], Object);
            }
            if (data.hasOwnProperty('simple')) {
                obj['simple'] = ChannelPackagingContentProtectionSimple.constructFromObject(data['simple']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ChannelPackagingContentProtectionAtlas} atlas
 */
ChannelPackagingContentProtection.prototype['atlas'] = undefined;

/**
 * @member {module:model/ChannelPackagingContentProtectionBulkFile} bulk_file
 */
ChannelPackagingContentProtection.prototype['bulk_file'] = undefined;

/**
 * @member {module:model/ChannelPackagingContentProtectionCommon} common
 */
ChannelPackagingContentProtection.prototype['common'] = undefined;

/**
 * @member {module:model/ChannelPackagingContentProtectionCpix} cpix
 */
ChannelPackagingContentProtection.prototype['cpix'] = undefined;

/**
 * @member {module:model/ChannelPackagingContentProtectionKeyRotation} key_rotation
 */
ChannelPackagingContentProtection.prototype['key_rotation'] = undefined;

/**
 * Only one of ['bulk_file', 'sample_aes', 'common'] may be set.
 * @member {Object} sample_aes
 */
ChannelPackagingContentProtection.prototype['sample_aes'] = undefined;

/**
 * @member {module:model/ChannelPackagingContentProtectionSimple} simple
 */
ChannelPackagingContentProtection.prototype['simple'] = undefined;






export default ChannelPackagingContentProtection;

