/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChannelTranscodeLoudness model module.
 * @module model/ChannelTranscodeLoudness
 * @version 0.0.0
 */
class ChannelTranscodeLoudness {
    /**
     * Constructs a new <code>ChannelTranscodeLoudness</code>.
     * Loudness normalization settings.
     * @alias module:model/ChannelTranscodeLoudness
     */
    constructor() { 
        
        ChannelTranscodeLoudness.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChannelTranscodeLoudness</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChannelTranscodeLoudness} obj Optional instance to populate.
     * @return {module:model/ChannelTranscodeLoudness} The populated <code>ChannelTranscodeLoudness</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChannelTranscodeLoudness();

            if (data.hasOwnProperty('dialog_intel')) {
                obj['dialog_intel'] = ApiClient.convertToType(data['dialog_intel'], 'Boolean');
            }
            if (data.hasOwnProperty('lkfs')) {
                obj['lkfs'] = ApiClient.convertToType(data['lkfs'], 'Number');
            }
            if (data.hasOwnProperty('lra')) {
                obj['lra'] = ApiClient.convertToType(data['lra'], 'Number');
            }
            if (data.hasOwnProperty('peak_limit')) {
                obj['peak_limit'] = ApiClient.convertToType(data['peak_limit'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Enable Dialog Intelligence. Only supported for (E)AC-3 encoders.
 * @member {Boolean} dialog_intel
 */
ChannelTranscodeLoudness.prototype['dialog_intel'] = undefined;

/**
 * Loudness normalization LKFS setting. Default value is -24.
 * @member {Number} lkfs
 */
ChannelTranscodeLoudness.prototype['lkfs'] = undefined;

/**
 * Loudness Range. Only supported for non-(E)AC-3 encoders. Default value is 7.0.
 * @member {Number} lra
 */
ChannelTranscodeLoudness.prototype['lra'] = undefined;

/**
 * Peak Limit. Default value is -2.0.
 * @member {Number} peak_limit
 */
ChannelTranscodeLoudness.prototype['peak_limit'] = undefined;






export default ChannelTranscodeLoudness;

