/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChannelTranscodeH264 model module.
 * @module model/ChannelTranscodeH264
 * @version 0.0.0
 */
class ChannelTranscodeH264 {
    /**
     * Constructs a new <code>ChannelTranscodeH264</code>.
     * Configure the encoder to use the H.264 codec. Only one of [&#39;H264Settings&#39;, &#39;H265Settings&#39;] may be set
     * @alias module:model/ChannelTranscodeH264
     */
    constructor() { 
        
        ChannelTranscodeH264.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChannelTranscodeH264</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChannelTranscodeH264} obj Optional instance to populate.
     * @return {module:model/ChannelTranscodeH264} The populated <code>ChannelTranscodeH264</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChannelTranscodeH264();

            if (data.hasOwnProperty('profile')) {
                obj['profile'] = ApiClient.convertToType(data['profile'], 'String');
            }
        }
        return obj;
    }


}

/**
 * H.264 video profile, which defines various encoder features and settings. See https://en.wikipedia.org/wiki/Advanced_Video_Coding#Profiles for details.
 * @member {module:model/ChannelTranscodeH264.ProfileEnum} profile
 */
ChannelTranscodeH264.prototype['profile'] = undefined;





/**
 * Allowed values for the <code>profile</code> property.
 * @enum {String}
 * @readonly
 */
ChannelTranscodeH264['ProfileEnum'] = {

    /**
     * value: "BASELINE"
     * @const
     */
    "BASELINE": "BASELINE",

    /**
     * value: "MAIN"
     * @const
     */
    "MAIN": "MAIN",

    /**
     * value: "HIGH"
     * @const
     */
    "HIGH": "HIGH",

    /**
     * value: "HIGH_10"
     * @const
     */
    "HIGH_10": "HIGH_10",

    /**
     * value: "HIGH_422"
     * @const
     */
    "HIGH_422": "HIGH_422"
};



export default ChannelTranscodeH264;

