/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChannelPackagingContentProtectionSimpleBasicAuth model module.
 * @module model/ChannelPackagingContentProtectionSimpleBasicAuth
 * @version 0.0.0
 */
class ChannelPackagingContentProtectionSimpleBasicAuth {
    /**
     * Constructs a new <code>ChannelPackagingContentProtectionSimpleBasicAuth</code>.
     * Only one of [&#39;basic_auth&#39;] may be set.
     * @alias module:model/ChannelPackagingContentProtectionSimpleBasicAuth
     */
    constructor() { 
        
        ChannelPackagingContentProtectionSimpleBasicAuth.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChannelPackagingContentProtectionSimpleBasicAuth</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChannelPackagingContentProtectionSimpleBasicAuth} obj Optional instance to populate.
     * @return {module:model/ChannelPackagingContentProtectionSimpleBasicAuth} The populated <code>ChannelPackagingContentProtectionSimpleBasicAuth</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChannelPackagingContentProtectionSimpleBasicAuth();

            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Plain text password for basic auth.
 * @member {String} password
 */
ChannelPackagingContentProtectionSimpleBasicAuth.prototype['password'] = undefined;

/**
 * Username for basic auth.
 * @member {String} username
 */
ChannelPackagingContentProtectionSimpleBasicAuth.prototype['username'] = undefined;






export default ChannelPackagingContentProtectionSimpleBasicAuth;

