/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChannelPublishingClosedCaptionStreams model module.
 * @module model/ChannelPublishingClosedCaptionStreams
 * @version 0.0.0
 */
class ChannelPublishingClosedCaptionStreams {
    /**
     * Constructs a new <code>ChannelPublishingClosedCaptionStreams</code>.
     * @alias module:model/ChannelPublishingClosedCaptionStreams
     */
    constructor() { 
        
        ChannelPublishingClosedCaptionStreams.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChannelPublishingClosedCaptionStreams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChannelPublishingClosedCaptionStreams} obj Optional instance to populate.
     * @return {module:model/ChannelPublishingClosedCaptionStreams} The populated <code>ChannelPublishingClosedCaptionStreams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChannelPublishingClosedCaptionStreams();

            if (data.hasOwnProperty('auto_select')) {
                obj['auto_select'] = ApiClient.convertToType(data['auto_select'], 'String');
            }
            if (data.hasOwnProperty('default')) {
                obj['default'] = ApiClient.convertToType(data['default'], 'String');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = ApiClient.convertToType(data['language'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Indicates that the client should play the captioning media selection group if the user has not indicated a user preference. If both auto_select and default are not set, the first captioning media selection group will be used.
 * @member {module:model/ChannelPublishingClosedCaptionStreams.AutoSelectEnum} auto_select
 */
ChannelPublishingClosedCaptionStreams.prototype['auto_select'] = undefined;

/**
 * Configures the captioning media selection group that will be played if the user has not indicated a user preference. If both auto_select and default are not set, the first captioning media selection group will be used.
 * @member {module:model/ChannelPublishingClosedCaptionStreams.DefaultEnum} default
 */
ChannelPublishingClosedCaptionStreams.prototype['default'] = undefined;

/**
 * Language code as RFC 5646, e.g. 'en' 'en-US'.
 * @member {String} language
 */
ChannelPublishingClosedCaptionStreams.prototype['language'] = undefined;

/**
 * Source stream name.
 * @member {String} name
 */
ChannelPublishingClosedCaptionStreams.prototype['name'] = undefined;





/**
 * Allowed values for the <code>auto_select</code> property.
 * @enum {String}
 * @readonly
 */
ChannelPublishingClosedCaptionStreams['AutoSelectEnum'] = {

    /**
     * value: "NO"
     * @const
     */
    "NO": "NO",

    /**
     * value: "YES"
     * @const
     */
    "YES": "YES"
};


/**
 * Allowed values for the <code>default</code> property.
 * @enum {String}
 * @readonly
 */
ChannelPublishingClosedCaptionStreams['DefaultEnum'] = {

    /**
     * value: "NO"
     * @const
     */
    "NO": "NO",

    /**
     * value: "YES"
     * @const
     */
    "YES": "YES"
};



export default ChannelPublishingClosedCaptionStreams;

