/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChannelPlaybackCmaf from './ChannelPlaybackCmaf';

/**
 * The ChannelPlayback model module.
 * @module model/ChannelPlayback
 * @version 0.0.0
 */
class ChannelPlayback {
    /**
     * Constructs a new <code>ChannelPlayback</code>.
     * @alias module:model/ChannelPlayback
     */
    constructor() { 
        
        ChannelPlayback.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChannelPlayback</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChannelPlayback} obj Optional instance to populate.
     * @return {module:model/ChannelPlayback} The populated <code>ChannelPlayback</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChannelPlayback();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('cmaf')) {
                obj['cmaf'] = ApiClient.convertToType(data['cmaf'], [ChannelPlaybackCmaf]);
            }
            if (data.hasOwnProperty('dash')) {
                obj['dash'] = ApiClient.convertToType(data['dash'], [ChannelPlaybackCmaf]);
            }
            if (data.hasOwnProperty('hls')) {
                obj['hls'] = ApiClient.convertToType(data['hls'], [ChannelPlaybackCmaf]);
            }
        }
        return obj;
    }


}

/**
 * An optional URL to a JSON Schema document describing this resource
 * @member {String} $schema
 */
ChannelPlayback.prototype['$schema'] = undefined;

/**
 * CMAF playback configurations
 * @member {Array.<module:model/ChannelPlaybackCmaf>} cmaf
 */
ChannelPlayback.prototype['cmaf'] = undefined;

/**
 * Dash playback configurations
 * @member {Array.<module:model/ChannelPlaybackCmaf>} dash
 */
ChannelPlayback.prototype['dash'] = undefined;

/**
 * HLS playback configurations
 * @member {Array.<module:model/ChannelPlaybackCmaf>} hls
 */
ChannelPlayback.prototype['hls'] = undefined;






export default ChannelPlayback;

