/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChannelPackagingContentProtectionSimplePublishPoints from './ChannelPackagingContentProtectionSimplePublishPoints';

/**
 * The ChannelPackagingContentProtectionSimple model module.
 * @module model/ChannelPackagingContentProtectionSimple
 * @version 0.0.0
 */
class ChannelPackagingContentProtectionSimple {
    /**
     * Constructs a new <code>ChannelPackagingContentProtectionSimple</code>.
     * Only one of [&#39;simple&#39;, &#39;atlas&#39;, &#39;cpix&#39;] may be set.
     * @alias module:model/ChannelPackagingContentProtectionSimple
     */
    constructor() { 
        
        ChannelPackagingContentProtectionSimple.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChannelPackagingContentProtectionSimple</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChannelPackagingContentProtectionSimple} obj Optional instance to populate.
     * @return {module:model/ChannelPackagingContentProtectionSimple} The populated <code>ChannelPackagingContentProtectionSimple</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChannelPackagingContentProtectionSimple();

            if (data.hasOwnProperty('publish_points')) {
                obj['publish_points'] = ApiClient.convertToType(data['publish_points'], [ChannelPackagingContentProtectionSimplePublishPoints]);
            }
            if (data.hasOwnProperty('require_publish')) {
                obj['require_publish'] = ApiClient.convertToType(data['require_publish'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Pub points where keys should be published. If multiple are specified, only one needs to succeed to consider the key successfully published.
 * @member {Array.<module:model/ChannelPackagingContentProtectionSimplePublishPoints>} publish_points
 */
ChannelPackagingContentProtectionSimple.prototype['publish_points'] = undefined;

/**
 * Indicates which publish points must succeed for segment publishing to use the keys.
 * @member {module:model/ChannelPackagingContentProtectionSimple.RequirePublishEnum} require_publish
 */
ChannelPackagingContentProtectionSimple.prototype['require_publish'] = undefined;





/**
 * Allowed values for the <code>require_publish</code> property.
 * @enum {String}
 * @readonly
 */
ChannelPackagingContentProtectionSimple['RequirePublishEnum'] = {

    /**
     * value: "ANY"
     * @const
     */
    "ANY": "ANY",

    /**
     * value: "ALL"
     * @const
     */
    "ALL": "ALL"
};



export default ChannelPackagingContentProtectionSimple;

