/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChannelPackagingContentProtectionBulkFile model module.
 * @module model/ChannelPackagingContentProtectionBulkFile
 * @version 0.0.0
 */
class ChannelPackagingContentProtectionBulkFile {
    /**
     * Constructs a new <code>ChannelPackagingContentProtectionBulkFile</code>.
     * Only one of [&#39;bulk_file&#39;, &#39;sample_aes&#39;, &#39;common&#39;] may be set.
     * @alias module:model/ChannelPackagingContentProtectionBulkFile
     */
    constructor() { 
        
        ChannelPackagingContentProtectionBulkFile.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChannelPackagingContentProtectionBulkFile</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChannelPackagingContentProtectionBulkFile} obj Optional instance to populate.
     * @return {module:model/ChannelPackagingContentProtectionBulkFile} The populated <code>ChannelPackagingContentProtectionBulkFile</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChannelPackagingContentProtectionBulkFile();

            if (data.hasOwnProperty('iv_rotation')) {
                obj['iv_rotation'] = ApiClient.convertToType(data['iv_rotation'], 'String');
            }
        }
        return obj;
    }


}

/**
 * How often the IV should be rotated and how it should be created
 * @member {module:model/ChannelPackagingContentProtectionBulkFile.IvRotationEnum} iv_rotation
 */
ChannelPackagingContentProtectionBulkFile.prototype['iv_rotation'] = undefined;





/**
 * Allowed values for the <code>iv_rotation</code> property.
 * @enum {String}
 * @readonly
 */
ChannelPackagingContentProtectionBulkFile['IvRotationEnum'] = {

    /**
     * value: "RANDOM_PER_KEY"
     * @const
     */
    "RANDOM_PER_KEY": "RANDOM_PER_KEY",

    /**
     * value: "PER_SEGMENT_NUMBER"
     * @const
     */
    "PER_SEGMENT_NUMBER": "PER_SEGMENT_NUMBER",

    /**
     * value: "UNIQUE_PER_SEGMENT"
     * @const
     */
    "UNIQUE_PER_SEGMENT": "UNIQUE_PER_SEGMENT"
};



export default ChannelPackagingContentProtectionBulkFile;

