/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChannelPackagingContentProtectionAtlas model module.
 * @module model/ChannelPackagingContentProtectionAtlas
 * @version 0.0.0
 */
class ChannelPackagingContentProtectionAtlas {
    /**
     * Constructs a new <code>ChannelPackagingContentProtectionAtlas</code>.
     * Only one of [&#39;simple&#39;, &#39;atlas&#39;, &#39;cpix&#39;] may be set.
     * @alias module:model/ChannelPackagingContentProtectionAtlas
     */
    constructor() { 
        
        ChannelPackagingContentProtectionAtlas.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChannelPackagingContentProtectionAtlas</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChannelPackagingContentProtectionAtlas} obj Optional instance to populate.
     * @return {module:model/ChannelPackagingContentProtectionAtlas} The populated <code>ChannelPackagingContentProtectionAtlas</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChannelPackagingContentProtectionAtlas();

            if (data.hasOwnProperty('asset_id')) {
                obj['asset_id'] = ApiClient.convertToType(data['asset_id'], 'String');
            }
            if (data.hasOwnProperty('company_id')) {
                obj['company_id'] = ApiClient.convertToType(data['company_id'], 'String');
            }
            if (data.hasOwnProperty('drms')) {
                obj['drms'] = ApiClient.convertToType(data['drms'], ['String']);
            }
            if (data.hasOwnProperty('widevine_v0_pssh_box')) {
                obj['widevine_v0_pssh_box'] = ApiClient.convertToType(data['widevine_v0_pssh_box'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * The Asset Identifier which was taken from the token entitlement service request.
 * @member {String} asset_id
 */
ChannelPackagingContentProtectionAtlas.prototype['asset_id'] = undefined;

/**
 * The Identifier of the Company that this token belongs.
 * @member {String} company_id
 */
ChannelPackagingContentProtectionAtlas.prototype['company_id'] = undefined;

/**
 * DRM system keys to request
 * @member {Array.<module:model/ChannelPackagingContentProtectionAtlas.DrmsEnum>} drms
 */
ChannelPackagingContentProtectionAtlas.prototype['drms'] = undefined;

/**
 * When TRUE the KeyID is not embedded in the pssh box which sets the version to 0. Defaults to generating v1 pssh_boxes that includes the key_id
 * @member {Boolean} widevine_v0_pssh_box
 */
ChannelPackagingContentProtectionAtlas.prototype['widevine_v0_pssh_box'] = undefined;





/**
 * Allowed values for the <code>drms</code> property.
 * @enum {String}
 * @readonly
 */
ChannelPackagingContentProtectionAtlas['DrmsEnum'] = {

    /**
     * value: "WIDEVINE"
     * @const
     */
    "WIDEVINE": "WIDEVINE",

    /**
     * value: "FAIRPLAY"
     * @const
     */
    "FAIRPLAY": "FAIRPLAY",

    /**
     * value: "PRIMETIME"
     * @const
     */
    "PRIMETIME": "PRIMETIME",

    /**
     * value: "PLAYREADY"
     * @const
     */
    "PLAYREADY": "PLAYREADY"
};



export default ChannelPackagingContentProtectionAtlas;

