/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChannelTags model module.
 * @module model/ChannelTags
 * @version 0.0.0
 */
class ChannelTags {
    /**
     * Constructs a new <code>ChannelTags</code>.
     * Use ChannelMetadata when possible instead of tags.
     * @alias module:model/ChannelTags
     */
    constructor() { 
        
        ChannelTags.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChannelTags</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChannelTags} obj Optional instance to populate.
     * @return {module:model/ChannelTags} The populated <code>ChannelTags</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChannelTags();

            if (data.hasOwnProperty('monitored')) {
                obj['monitored'] = ApiClient.convertToType(data['monitored'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Indicates whether this channel is monitored by automation.
 * @member {Boolean} monitored
 */
ChannelTags.prototype['monitored'] = undefined;






export default ChannelTags;

