/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChannelPlaybackContentProtection from './ChannelPlaybackContentProtection';

/**
 * The ChannelPlaybackCmaf model module.
 * @module model/ChannelPlaybackCmaf
 * @version 0.0.0
 */
class ChannelPlaybackCmaf {
    /**
     * Constructs a new <code>ChannelPlaybackCmaf</code>.
     * @alias module:model/ChannelPlaybackCmaf
     * @param url {String} Playback URL
     */
    constructor(url) { 
        
        ChannelPlaybackCmaf.initialize(this, url);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, url) { 
        obj['url'] = url;
    }

    /**
     * Constructs a <code>ChannelPlaybackCmaf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChannelPlaybackCmaf} obj Optional instance to populate.
     * @return {module:model/ChannelPlaybackCmaf} The populated <code>ChannelPlaybackCmaf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChannelPlaybackCmaf();

            if (data.hasOwnProperty('content_protection')) {
                obj['content_protection'] = ChannelPlaybackContentProtection.constructFromObject(data['content_protection']);
            }
            if (data.hasOwnProperty('partial_presentations')) {
                obj['partial_presentations'] = ApiClient.convertToType(data['partial_presentations'], ['String']);
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ChannelPlaybackContentProtection} content_protection
 */
ChannelPlaybackCmaf.prototype['content_protection'] = undefined;

/**
 * Partial Presentation Playback URLs
 * @member {Array.<String>} partial_presentations
 */
ChannelPlaybackCmaf.prototype['partial_presentations'] = undefined;

/**
 * Playback URL
 * @member {String} url
 */
ChannelPlaybackCmaf.prototype['url'] = undefined;






export default ChannelPlaybackCmaf;

