/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InsertMetadataRequest model module.
 * @module model/InsertMetadataRequest
 * @version 0.0.0
 */
class InsertMetadataRequest {
    /**
     * Constructs a new <code>InsertMetadataRequest</code>.
     * @alias module:model/InsertMetadataRequest
     * @param payload {String} ID3 payload as UTF-8 text
     */
    constructor(payload) { 
        
        InsertMetadataRequest.initialize(this, payload);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, payload) { 
        obj['payload'] = payload;
    }

    /**
     * Constructs a <code>InsertMetadataRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InsertMetadataRequest} obj Optional instance to populate.
     * @return {module:model/InsertMetadataRequest} The populated <code>InsertMetadataRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InsertMetadataRequest();

            if (data.hasOwnProperty('payload')) {
                obj['payload'] = ApiClient.convertToType(data['payload'], 'String');
            }
        }
        return obj;
    }


}

/**
 * ID3 payload as UTF-8 text
 * @member {String} payload
 */
InsertMetadataRequest.prototype['payload'] = undefined;






export default InsertMetadataRequest;

