/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InsertMetadataResult model module.
 * @module model/InsertMetadataResult
 * @version 0.0.0
 */
class InsertMetadataResult {
    /**
     * Constructs a new <code>InsertMetadataResult</code>.
     * @alias module:model/InsertMetadataResult
     * @param presentationTime {Date} The media stream timestamp for where the transcoder inserted the metadata
     */
    constructor(presentationTime) { 
        
        InsertMetadataResult.initialize(this, presentationTime);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, presentationTime) { 
        obj['presentation_time'] = presentationTime;
    }

    /**
     * Constructs a <code>InsertMetadataResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InsertMetadataResult} obj Optional instance to populate.
     * @return {module:model/InsertMetadataResult} The populated <code>InsertMetadataResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InsertMetadataResult();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('presentation_time')) {
                obj['presentation_time'] = ApiClient.convertToType(data['presentation_time'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * An optional URL to a JSON Schema document describing this resource
 * @member {String} $schema
 */
InsertMetadataResult.prototype['$schema'] = undefined;

/**
 * The media stream timestamp for where the transcoder inserted the metadata
 * @member {Date} presentation_time
 */
InsertMetadataResult.prototype['presentation_time'] = undefined;






export default InsertMetadataResult;

