/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChannelIngestSlate from './ChannelIngestSlate';
import PutChannelRequestIngestSource from './PutChannelRequestIngestSource';

/**
 * The PutChannelRequestIngest model module.
 * @module model/PutChannelRequestIngest
 * @version 0.0.0
 */
class PutChannelRequestIngest {
    /**
     * Constructs a new <code>PutChannelRequestIngest</code>.
     * Ingest configures inputs for the transcoder.
     * @alias module:model/PutChannelRequestIngest
     * @param source {module:model/PutChannelRequestIngestSource} 
     */
    constructor(source) { 
        
        PutChannelRequestIngest.initialize(this, source);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, source) { 
        obj['source'] = source;
    }

    /**
     * Constructs a <code>PutChannelRequestIngest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PutChannelRequestIngest} obj Optional instance to populate.
     * @return {module:model/PutChannelRequestIngest} The populated <code>PutChannelRequestIngest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PutChannelRequestIngest();

            if (data.hasOwnProperty('slate')) {
                obj['slate'] = ChannelIngestSlate.constructFromObject(data['slate']);
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = PutChannelRequestIngestSource.constructFromObject(data['source']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ChannelIngestSlate} slate
 */
PutChannelRequestIngest.prototype['slate'] = undefined;

/**
 * @member {module:model/PutChannelRequestIngestSource} source
 */
PutChannelRequestIngest.prototype['source'] = undefined;






export default PutChannelRequestIngest;

