/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Scte35 model module.
 * @module model/Scte35
 * @version 0.0.0
 */
class Scte35 {
    /**
     * Constructs a new <code>Scte35</code>.
     * @alias module:model/Scte35
     * @param payload {String} The SCTE-35 payload, encoded as base-64 in JSON or binary data in CBOR
     */
    constructor(payload) { 
        
        Scte35.initialize(this, payload);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, payload) { 
        obj['payload'] = payload;
    }

    /**
     * Constructs a <code>Scte35</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Scte35} obj Optional instance to populate.
     * @return {module:model/Scte35} The populated <code>Scte35</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Scte35();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = ApiClient.convertToType(data['payload'], 'String');
            }
        }
        return obj;
    }


}

/**
 * An optional URL to a JSON Schema document describing this resource
 * @member {String} $schema
 */
Scte35.prototype['$schema'] = undefined;

/**
 * The SCTE-35 payload, encoded as base-64 in JSON or binary data in CBOR
 * @member {String} payload
 */
Scte35.prototype['payload'] = undefined;






export default Scte35;

