/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Slate model module.
 * @module model/Slate
 * @version 0.0.0
 */
class Slate {
    /**
     * Constructs a new <code>Slate</code>.
     * @alias module:model/Slate
     * @param uri {String} Slate url
     */
    constructor(uri) { 
        
        Slate.initialize(this, uri);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, uri) { 
        obj['uri'] = uri;
    }

    /**
     * Constructs a <code>Slate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Slate} obj Optional instance to populate.
     * @return {module:model/Slate} The populated <code>Slate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Slate();

            if (data.hasOwnProperty('$schema')) {
                obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
            if (data.hasOwnProperty('uri')) {
                obj['uri'] = ApiClient.convertToType(data['uri'], 'String');
            }
        }
        return obj;
    }


}

/**
 * An optional URL to a JSON Schema document describing this resource
 * @member {String} $schema
 */
Slate.prototype['$schema'] = undefined;

/**
 * Slate duration (ms)
 * @member {Number} duration
 * @default 0
 */
Slate.prototype['duration'] = 0;

/**
 * Slate url
 * @member {String} uri
 */
Slate.prototype['uri'] = undefined;






export default Slate;

