/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SpliceInsertEndSignal model module.
 * @module model/SpliceInsertEndSignal
 * @version 0.0.0
 */
class SpliceInsertEndSignal {
    /**
     * Constructs a new <code>SpliceInsertEndSignal</code>.
     * @alias module:model/SpliceInsertEndSignal
     * @param eventId {Number} Event ID
     */
    constructor(eventId) { 
        
        SpliceInsertEndSignal.initialize(this, eventId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, eventId) { 
        obj['event_id'] = eventId;
    }

    /**
     * Constructs a <code>SpliceInsertEndSignal</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SpliceInsertEndSignal} obj Optional instance to populate.
     * @return {module:model/SpliceInsertEndSignal} The populated <code>SpliceInsertEndSignal</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SpliceInsertEndSignal();

            if (data.hasOwnProperty('event_id')) {
                obj['event_id'] = ApiClient.convertToType(data['event_id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Event ID
 * @member {Number} event_id
 */
SpliceInsertEndSignal.prototype['event_id'] = undefined;






export default SpliceInsertEndSignal;

