/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SpliceInsertStartSignal model module.
 * @module model/SpliceInsertStartSignal
 * @version 0.0.0
 */
class SpliceInsertStartSignal {
    /**
     * Constructs a new <code>SpliceInsertStartSignal</code>.
     * @alias module:model/SpliceInsertStartSignal
     * @param eventId {Number} Event ID
     */
    constructor(eventId) { 
        
        SpliceInsertStartSignal.initialize(this, eventId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, eventId) { 
        obj['event_id'] = eventId;
    }

    /**
     * Constructs a <code>SpliceInsertStartSignal</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SpliceInsertStartSignal} obj Optional instance to populate.
     * @return {module:model/SpliceInsertStartSignal} The populated <code>SpliceInsertStartSignal</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SpliceInsertStartSignal();

            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
            }
            if (data.hasOwnProperty('event_id')) {
                obj['event_id'] = ApiClient.convertToType(data['event_id'], 'Number');
            }
            if (data.hasOwnProperty('slate_uri')) {
                obj['slate_uri'] = ApiClient.convertToType(data['slate_uri'], 'String');
            }
            if (data.hasOwnProperty('upids')) {
                obj['upids'] = ApiClient.convertToType(data['upids'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * Splice duration (ms).  If no duration or a duration of 0 then the splice is indifinite.
 * @member {Number} duration
 * @default 0
 */
SpliceInsertStartSignal.prototype['duration'] = 0;

/**
 * Event ID
 * @member {Number} event_id
 */
SpliceInsertStartSignal.prototype['event_id'] = undefined;

/**
 * Slate url
 * @member {String} slate_uri
 */
SpliceInsertStartSignal.prototype['slate_uri'] = undefined;

/**
 * UPIDs
 * @member {Array.<String>} upids
 */
SpliceInsertStartSignal.prototype['upids'] = undefined;






export default SpliceInsertStartSignal;

