/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Isp);
  }
}(this, function(expect, Isp) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Isp.ChannelSignalingBlackoutSettings();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ChannelSignalingBlackoutSettings', function() {
    it('should create an instance of ChannelSignalingBlackoutSettings', function() {
      // uncomment below and update the code to test ChannelSignalingBlackoutSettings
      //var instance = new Isp.ChannelSignalingBlackoutSettings();
      //expect(instance).to.be.a(Isp.ChannelSignalingBlackoutSettings);
    });

    it('should have the property defaultBlackoutSlateUrl (base name: "default_blackout_slate_url")', function() {
      // uncomment below and update the code to test the property defaultBlackoutSlateUrl
      //var instance = new Isp.ChannelSignalingBlackoutSettings();
      //expect(instance).to.be();
    });

    it('should have the property forceBlackoutSegments (base name: "force_blackout_segments")', function() {
      // uncomment below and update the code to test the property forceBlackoutSegments
      //var instance = new Isp.ChannelSignalingBlackoutSettings();
      //expect(instance).to.be();
    });

    it('should have the property honorWebDeliveryRestriction (base name: "honor_web_delivery_restriction")', function() {
      // uncomment below and update the code to test the property honorWebDeliveryRestriction
      //var instance = new Isp.ChannelSignalingBlackoutSettings();
      //expect(instance).to.be();
    });

    it('should have the property slates (base name: "slates")', function() {
      // uncomment below and update the code to test the property slates
      //var instance = new Isp.ChannelSignalingBlackoutSettings();
      //expect(instance).to.be();
    });

  });

}));
