/**
 * iStreamPlanet Channels API
 * This API provides a way to list, create, and run channels.  Channels consist of inputs (ingest), transcoding settings like codecs and bitrates, and outputs (publishing).  List calls use cursor-based pagination with [RFC 5988](https://tools.ietf.org/html/rfc5988) Link headers. Clients *should* read this header and follow the next link to read all pages of results. 
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@istreamplanet.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Isp);
  }
}(this, function(expect, Isp) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Isp.ChannelPublishingHls();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ChannelPublishingHls', function() {
    it('should create an instance of ChannelPublishingHls', function() {
      // uncomment below and update the code to test ChannelPublishingHls
      //var instance = new Isp.ChannelPublishingHls();
      //expect(instance).to.be.a(Isp.ChannelPublishingHls);
    });

    it('should have the property audioOnlyVariants (base name: "audio_only_variants")', function() {
      // uncomment below and update the code to test the property audioOnlyVariants
      //var instance = new Isp.ChannelPublishingHls();
      //expect(instance).to.be();
    });

    it('should have the property gapTags (base name: "gap_tags")', function() {
      // uncomment below and update the code to test the property gapTags
      //var instance = new Isp.ChannelPublishingHls();
      //expect(instance).to.be();
    });

    it('should have the property masterPublishFrequencySecs (base name: "master_publish_frequency_secs")', function() {
      // uncomment below and update the code to test the property masterPublishFrequencySecs
      //var instance = new Isp.ChannelPublishingHls();
      //expect(instance).to.be();
    });

    it('should have the property masterUrlType (base name: "master_url_type")', function() {
      // uncomment below and update the code to test the property masterUrlType
      //var instance = new Isp.ChannelPublishingHls();
      //expect(instance).to.be();
    });

    it('should have the property mediaUrlType (base name: "media_url_type")', function() {
      // uncomment below and update the code to test the property mediaUrlType
      //var instance = new Isp.ChannelPublishingHls();
      //expect(instance).to.be();
    });

    it('should have the property partialPresentations (base name: "partial_presentations")', function() {
      // uncomment below and update the code to test the property partialPresentations
      //var instance = new Isp.ChannelPublishingHls();
      //expect(instance).to.be();
    });

    it('should have the property pdtOnEverySegment (base name: "pdt_on_every_segment")', function() {
      // uncomment below and update the code to test the property pdtOnEverySegment
      //var instance = new Isp.ChannelPublishingHls();
      //expect(instance).to.be();
    });

    it('should have the property signalingFormats (base name: "signaling_formats")', function() {
      // uncomment below and update the code to test the property signalingFormats
      //var instance = new Isp.ChannelPublishingHls();
      //expect(instance).to.be();
    });

    it('should have the property utcInSegmentTitle (base name: "utc_in_segment_title")', function() {
      // uncomment below and update the code to test the property utcInSegmentTitle
      //var instance = new Isp.ChannelPublishingHls();
      //expect(instance).to.be();
    });

  });

}));
